version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: motorsportpage_database_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      #Al montar ./src/database en /docker-entrypoint-initdb.d, MySQL ejecuta automáticamente todos los archivos .sql en este directorio solo durante la primera inicialización (cuando la base de datos no existe).
      - ./src/database/db.init.sql:/docker-entrypoint-initdb.d/db.init.sql
    networks:
      - motorsportpage-net

  web:
    image: motorsportpage_app_image
    container_name: motorsportpage_web_app
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./public:/var/www/html #Ésta linea debo comentarla en produccion
      - ./src:/var/www/src #Ésta linea debo comentarla en produccion
    depends_on:
      - db
    networks:
      - motorsportpage-net

networks:
  motorsportpage-net:
    driver: bridge
